import type { Metadata } from "next";
import "./globals.css";
import amazonpaws from "@/resources/images/amazonpaws.svg";
import Image from "next/image";
import Link from "next/link";

export const dynamic = 'force-dynamic';

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

  alternates: {
    types: {
      "application/atom+xml": "/feeds/atom",
      "application/rss+xml": "/feeds/rss"
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link className="logo" href="/">
            <Image src={amazonpaws} alt="Amazon Logo, but with paws." height="100" />
            <div>
              <h1>Amazon Paws</h1>
              <p style={{margin: 0}}>The paw prints Amazon leaves on the world.</p>
            </div>
          </Link>
        </header>
        <main>
        {children}
        </main>
        <footer>
        </footer>
      </body>
    </html>
  );
}
